image: docker:18.09
services:
  - docker:18.09-dind

stages:
- build
- test
- release

variables:
  TEST_IMAGE: registry.shieldsuk.me/uomesports/uom-static:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: registry.shieldsuk.me/uomesports/uom-static:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.shieldsuk.me

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

test:
  stage: test
  script:
    - docker pull $TEST_IMAGE
    - docker run $TEST_IMAGE npm run lint #TODO: write actual tests

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - prod